config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :kinds
  resources :users 
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "kinds#index"

end

app/models/kind.rb
# == Schema Information
#
# Table name: kinds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Kind < ActiveRecord::Base
  KINDS_STRING = ["Ruby","JavaScript","HTML","CSS"]

  has_many :snippets, dependent: :nullify

  validates :name, presence: true, uniqueness: true
end

app/controllers/kinds_controller.rb
# == Schema Information
#
# Table name: kinds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class KindsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_action :set_kind, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:index, :show]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
    @snippets = @kind.snippets.filtered_result(uid)
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_kind
    @kind = Kind.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kind_params
    params.require(:kind).permit(:name)
  end

  def authorize_user
    unless can? :manage, @kind 
      redirect_to root_path, alert: "access denied!"
    end
  end
end

app/helpers/kinds_helper.rb
# == Schema Information
#
# Table name: kinds
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_for @kind, :html => { :class => "form-horizontal kind" } do |f| %>

  <% if @kind.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@kind.errors.count, "error") %> prohibited this kind from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @kind.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                kinds_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/kinds/edit.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kinds/index.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<% @kinds.each do |kind| %>
<h1><%= link_to "#{kind.name} (#{kind.snippets.length})", kind_path(kind) %></h1>
<div>
<% if can? :manage, kind %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                         edit_kind_path(kind), :class => 'btn btn-default btn-xs' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              kind_path(kind),
              :method => :delete,
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-xs btn-danger' %>
  <% end %>
<% end %>
</div>
<br>
<% if can? :manage, Kind %>
  <div>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                          new_kind_path,
                          :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/kinds/new.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kinds/show.html.erb
<h1><%= @kind.name %></h1>

<%= link_to t('.back', :default => t("helpers.links.back")),
              kinds_path, :class => 'btn btn-default'  %>
<% if can? :manage, @kind %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_kind_path(@kind), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                kind_path(@kind),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>

<%= render :partial => '/snippets/snippets' %>