config/routes.rb
Rails.application.routes.draw do
  resources :snippets
  resources :kinds
  resources :users 
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  root "kinds#index"

end

app/models/snippet.rb
# == Schema Information
#
# Table name: snippets
#
#  id         :integer          not null, primary key
#  title      :string
#  work       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kind_id    :integer
#  user_id    :integer
#

class Snippet < ActiveRecord::Base
  belongs_to :kind
  belongs_to :user

  validates :title, presence: true, uniqueness: true
  validates :work, presence: true
  # check this below
  validates :kind_id, presence: true

  def self.filtered_result(uid)
    if uid
      where("is_private = FALSE OR (is_private = TRUE AND user_id = ?)", uid)
    else
      where("is_private = FALSE")
    end
  end

  delegate :full_name, to: :user, prefix: true, allow_nil: :true
end

app/controllers/snippets_controller.rb
# == Schema Information
#
# Table name: snippets
#
#  id         :integer          not null, primary key
#  title      :string
#  work       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kind_id    :integer
#  user_id    :integer
#

class SnippetsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_snippet, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :destroy, :update]
  
  def new
    @snippet = Snippet.new
  end

  def create
    @snippet      = Snippet.new(snippet_params)
    @snippet.user = current_user

    if @snippet.save
      # sends a empty HTTP 200
      # render nothing: true
      redirect_to @snippet, notice: "New snippet created!"
    else
      flash[:alert] = "Error, please check below"
      render :new
    end
  end

  def show
    unless can? :read, @snippet 
      redirect_to root_path, alert: "access denied!"
    end
    
  end

  def index
    # refactor, ? can be nil
    @snippets = Snippet.filtered_result(uid)
    # if user_signed_in?
    #   @snippets = Snippet.where("is_private = false OR (is_private = true AND user_id = ?)", current_user.id)
    # else
    #   @snippets = Snippet.where("is_private = false")
    # end
  end

  def edit
    
  end

  def update
    if @snippet.update snippet_params
      redirect_to @snippet, notice: "Snippet updated!"
    else
      flash[:alert] = "Error, please check below"
      render :edit
    end
  end

  def destroy
    if @snippet.destroy
      redirect_to snippets_path, notice: "Snippet deleted."
    else
      flash[:alert] = "Error!"
      render @snippet
    end
  end

  private 

  def snippet_params
    params.require(:snippet).permit(:title, :work, :kind_id, :is_private)
  end

  def find_snippet
    @snippet = Snippet.find params[:id]
    # Rescue the specific error to supress it to make a test fail.
    # rescue ActiveRecord::RecordNotFound => e

  end

  def authorize_user
    #if @question.user != current_user
    unless can? :manage, @snippet 
      redirect_to root_path, alert: "access denied!"
    end
  end
end

app/helpers/snippets_helper.rb
# == Schema Information
#
# Table name: snippets
#
#  id         :integer          not null, primary key
#  title      :string
#  work       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  kind_id    :integer
#  user_id    :integer
#

class CodeRayify < Redcarpet::Render::HTML
  def block_code(code, language)
    CodeRay.scan(code, language).div(line_numbers: :table)
  end
end

module SnippetsHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true
      # link_attributes: { rel: 'nofollow', target: "_blank" }
      # space_after_headers: true
      # prettify: true
    }

    extensions = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      strikethrough: true,
      lax_spacing: true,
      superscript: true
    }

    # renderer = Redcarpet::Render::HTML.new(options)
    coderayified = CodeRayify.new(options)
    markdown = Redcarpet::Markdown.new(coderayified, extensions)

    markdown.render(text).html_safe
  end
end

app/views/snippets/_form.html.erb
<%= form_for @snippet, :html => { :class => "form-horizontal snippet" } do |f| %>

  <% if @snippet.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @snippet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :work, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :work, :class => 'form-control' %>
    </div>
    <%=f.error_span(:work) %>
  </div>
  <div class="form-group">
    <%= f.label :kind_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:kind_id, Kind.order("name"), :id, :name, {}, {class: 'form-control'}) %>
    <%=f.error_span(:kind_id) %>
  </div>
  <div class="form-group">
    <%= f.label :is_private, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :is_private, :class => 'form-control' %>
    <%=f.error_span(:is_private) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                snippets_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/snippets/_snippets.html.erb
<% @snippets.each do |snippet| %>
  <div>
    <h1><%= link_to snippet.title, snippet_path(snippet) %></h1>
    <div><%= markdown(snippet.work) %></div>
    <dl>
      <dt>Kind: </dt>
      <dd><%= snippet.kind.name %></dd>
    </dl>
    <dl>
      <dt>Created at: </dt>
      <dd><%=l snippet.created_at %></dd>
    </dl>
    <dl>
      <dt>Created by: </dt>
      <dd><%= snippet.user_full_name %></dd>
    </dl>
    <% if can? :manage, snippet %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_snippet_path(snippet), :class => 'btn btn-default btn-xs' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  snippet_path(snippet),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-xs btn-danger' %>
    <% end %>
    <hr>
  </div>
<% end %>

app/views/snippets/edit.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snippets/index.html.erb
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_snippet_path,
            :class => 'btn btn-primary' %>

<%= render :partial => 'snippets' %>

app/views/snippets/new.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/snippets/show.html.erb
<%- model_class = Snippet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<%= link_to t('.back', :default => t("helpers.links.back")),
              snippets_path, :class => 'btn btn-default'  %>
<% if can? :manage, @snippet %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_snippet_path(@snippet), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                snippet_path(@snippet),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @snippet.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:work) %>:</strong></dt>
  <dd><%= markdown(@snippet.work) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kind_id) %>:</strong></dt>
  <dd><%= @snippet.kind.name %></dd>
</dl>